name: firstworkflow
on: workflow_dispatch #manually trigger the event
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello"
      - name: print bye
        run: echo "bye"
  second-job:
  #needs this will make second job to run after first job
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: print hi
        run: echo "goodmorning"
      - name: print bye
        run: echo "goodnight"  
