name: firstworkflow
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello everyone"
      - name: print goodbye
        run: echo "Done-bye"
      - name: print logout
        run: echo "looged out"
